{
	"version": 1585327702,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/neige-sheet0.png",
		"images/neige-sheet1.png",
		"images/neige-sheet2.png",
		"images/neige-sheet3.png",
		"images/neige-sheet4.png",
		"images/neige-sheet5.png",
		"images/neige-sheet6.png",
		"images/neige-sheet7.png",
		"images/neige-sheet8.png",
		"images/neige-sheet9.png",
		"images/neige-sheet10.png",
		"images/neige-sheet11.png",
		"images/neige-sheet12.png",
		"images/neige-sheet13.png",
		"images/nuage-sheet0.png",
		"images/sol-sheet0.png",
		"images/cieletoile-sheet0.png",
		"images/flocon1-sheet0.png",
		"images/flocon2-sheet0.png",
		"images/rudolf-sheet0.png",
		"images/rudolf-sheet1.png",
		"images/particles.png",
		"images/spawn-sheet0.png",
		"images/sprite-sheet0.png",
		"images/facebook-sheet0.png",
		"images/facebook-sheet1.png",
		"images/facebook-sheet2.png",
		"images/sprite2-sheet0.png",
		"media/coin4.m4a",
		"media/coin4.ogg",
		"media/wintery loop.m4a",
		"media/wintery loop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}